//{{NO_DEPENDENCIES}}
// fichier Include Microsoft Visual C++.
// Utilisé par ColorizingDMD.rc
//
#define IDC_MYICON                      2
#define IDD_COLORIZINGDMD_DIALOG        102
#define IDI_CROM                        103
#define IDC_POINTER                     104
#define IDM_EXIT                        105
#define IDC_NODROP                      106
#define IDC_COLORIZINGDMD               109
#define IDR_ACCEL                       133
#define IDB_PNG9                        168
#define IDB_PNG1                        172
#define IDB_COLM                        172
#define IDI_ADDTXT                      173
#define IDI_COLMODE                     174
#define IDI_NEW                         175
#define IDI_ORGMODE                     176
#define IDI_OPEN                        178
#define IDI_SAVE                        179
#define IDI_UNDO                        180
#define IDI_ICON1                       181
#define IDI_REDO                        181
#define IDI_SELALL                      185
#define IDI_SELMASK                     186
#define IDI_ICON4                       187
#define IDI_SELMOVE                     187
#define IDD_ORGDLG                      189
#define IDD_COLDLG                      190
#define IDI_ICON2                       193
#define IDI_COLSET                      193
#define IDD_COLSET                      194
#define IDI_DRAWCERC                    196
#define IDI_DRAWPOINT                   197
#define IDI_DRAWRECT                    198
#define IDI_DRAWLINE                    199
#define IDI_FILL                        200
#define IDI_COLTOSEL                    201
#define IDI_COLPICK                     202
#define IDI_ADDMASK                     203
#define IDI_DELMASK                     204
#define IDI_MAGICWAND                   205
#define IDD_ASKNAME                     208
#define IDI_ICON3                       209
#define IDI_SEARCH                      209
#define IDD_SPRDLG                      209
#define IDD_DETSPR                      209
#define IDI_DELSAMEFR                   210
#define IDI_ICON5                       212
#define IDI_SELSAMEFR                   212
#define IDI_COPY                        214
#define IDI_ICON7                       215
#define IDI_PASTE                       215
#define IDC_CURSOR1                     233
#define IDI_ADDTAB                      234
#define IDI_DELTAB                      235
#define IDI_4COLSCOPY                   237
#define IDI_64COLSCOPY                  238
#define IDI_COLTODYNA                   239
#define IDI_ICON6                       240
#define IDI_ICON8                       243
#define IDI_INVERTSEL                   243
#define IDI_ADDSPR                      244
#define IDI_DELSPR                      245
#define IDI_ICON9                       246
#define IDI_FINDDWORD                   246
#define IDI_DELFRAME                    248
#define IDI_DELALLSAME                  249
#define IDI_ICON11                      250
#define IDI_MOVESECTION                 250
#define IDI_ADDSPRFR                    251
#define IDI_SPOTOFF                     252
#define IDI_SPOTON                      253
#define IDI_DELDETSPR                   254
#define IDI_ICON10                      255
#define IDI_SPRTOFRAME                  255
#define IDI_TRIALPHA                    256
#define IDI_DELSELSAME                  257
#define IDD_FILTERS                     258
#define IDI_NIGHTDAY                    259
#define IDD_IMGDLG                      259
#define IDB_PNG2                        261
#define IDI_CLIPIMAGE                   262
#define IDI_DELIMAGE                    263
#define IDI_LOADIMAGE                   264
#define IDI_ZOOMIN                      265
#define IDI_ZOOMOUT                     266
#define IDI_DOWNSCALE                   267
#define IDI_UPSCALE                     268
#define IDC_COLMODE                     1000
#define IDC_COLMODE2                    1001
#define IDC_NEW                         1001
#define IDC_COLMODE3                    1002
#define IDC_ADDTXT                      1002
#define IDC_COLMODE4                    1003
#define IDC_OPEN                        1003
#define IDC_COLMODE5                    1004
#define IDC_SAVE                        1004
#define IDC_COLMODE6                    1005
#define IDC_UNDO                        1005
#define IDC_COLMODE7                    1006
#define IDC_REDO                        1006
#define IDC_COLMODE8                    1007
#define IDC_HASHMODE                    1007
#define IDC_ADDTOFRAME                  1007
#define IDC_COLMODE9                    1008
#define IDC_COMPMASK                    1008
#define IDC_COLMODE10                   1009
#define IDC_MOVMASK                     1009
#define IDC_ORGMODE                     1011
#define IDC_CMID                        1012
#define IDC_DRAWPOINT                   1012
#define IDC_MMID                        1013
#define IDC_DRAWLINE                    1013
#define IDC_DRAWRECT                    1014
#define IDC_COMBO1                      1015
#define IDC_DRAWCIRC                    1015
#define IDC_FILL                        1016
#define IDC_COPY                        1017
#define IDC_DELDETSPR                   1017
#define IDC_COLSET                      1018
#define IDC_TOFRAME                     1018
#define IDC_ZOOMIN                      1018
#define IDC_NOMCOLSET1                  1019
#define IDC_DRAWPOINT2                  1019
#define IDC_COPYCOLS                    1019
#define IDC_ZOOMOUT                     1019
#define IDC_NOMCOLSET2                  1020
#define IDC_PASTE                       1020
#define IDC_PASTECUR                    1020
#define IDC_NOMCOLSET3                  1021
#define IDC_PASTE2                      1021
#define IDC_NIGHTDAY                    1021
#define IDC_NOMCOLSET4                  1022
#define IDC_NOMCOLSET5                  1023
#define IDC_DYNACOLSET                  1023
#define IDC_NOMCOLSET6                  1024
#define IDC_COLPICK                     1024
#define IDC_NOMCOLSET7                  1025
#define IDC_NOMCOLSET8                  1026
#define IDC_SBV                         1027
#define IDC_SETSET1                     1028
#define IDC_SETSET2                     1029
#define IDC_SETSET3                     1030
#define IDC_SETSET4                     1031
#define IDC_SETSET5                     1032
#define IDC_SETSET6                     1033
#define IDC_SETSET7                     1034
#define IDC_SETSET8                     1035
#define IDC_COL1SET1                    1036
#define IDC_COLORS                      1036
#define IDC_COL4SET8                    1037
#define IDC_MASKLIST                    1038
#define IDC_MASKLIST2                   1039
#define IDC_COL1SET2                    1041
#define IDC_4COLMODE2                   1041
#define IDC_POINTMASK                   1042
#define IDC_RECTMASK                    1043
#define IDC_ZONEMASK                    1044
#define IDC_FILLED                      1045
#define IDC_DELSAMEFR                   1046
#define IDC_SAMEFRAME                   1047
#define IDC_NAME                        1048
#define IDC_DELFRAME                    1048
#define IDC_CHECKFRAMES                 1049
#define IDC_DELALLSAMEFR                1049
#define IDC_SELSAMEFR                   1050
#define IDC_DELSELSAMEFR                1050
#define IDC_NOSETCOL                    1051
#define IDC_CHANGECOLSET                1052
#define IDC_STRY                        1052
#define IDC_STRY2                       1053
#define IDC_STRY3                       1054
#define IDC_STRY4                       1055
#define IDC_STRY12                      1056
#define IDC_STRY5                       1057
#define IDC_STRY14                      1057
#define IDC_STRY6                       1058
#define IDC_STRY17                      1058
#define IDC_STRY7                       1059
#define IDC_STRY18                      1059
#define IDC_STRY8                       1060
#define IDC_STRY19                      1060
#define IDC_STRY9                       1061
#define IDC_STRY10                      1062
#define IDC_SHAPEMODE                   1063
#define IDC_STRY11                      1063
#define IDC_STRY13                      1064
#define IDC_COLTODYNA                   1065
#define IDC_SECTIONLIST                 1066
#define IDC_SECTIONLIST2                1066
#define IDC_DELSECTION                  1067
#define IDC_ADDSECTION                  1068
#define IDC_SECTIONNAME                 1069
#define IDC_COPYCOLS2                   1070
#define IDC_1COLMODE                    1071
#define IDC_4COLMODE                    1072
#define IDC_GRADMODE                    1073
#define IDC_GRADMODEB                   1074
#define IDC_COL1                        1075
#define IDC_COL2                        1076
#define IDC_COL3                        1077
#define IDC_COL4                        1078
#define IDC_COL5                        1079
#define IDC_COL6                        1080
#define IDC_COL7                        1081
#define IDC_COL8                        1082
#define IDC_COL9                        1083
#define IDC_COL10                       1084
#define IDC_COL11                       1085
#define IDC_COL12                       1086
#define IDC_COL13                       1087
#define IDC_COL14                       1088
#define IDC_COL15                       1089
#define IDC_COL16                       1090
#define IDC_DYNACOL1                    1091
#define IDC_SPRITENAME                  1091
#define IDC_DYNACOL2                    1092
#define IDC_SPRITELIST                  1092
#define IDC_DYNACOL3                    1093
#define IDC_ADDSPRITE                   1093
#define IDC_DYNACOL4                    1094
#define IDC_DELSPRITE                   1094
#define IDC_DYNACOL5                    1095
#define IDC_STRY1                       1095
#define IDC_DYNACOL6                    1096
#define IDC_ISDWORD                     1096
#define IDC_DELSPR                      1096
#define IDC_DETSPR                      1096
#define IDC_DYNACOL7                    1097
#define IDC_DYNACOL8                    1098
#define IDC_DYNACOL9                    1099
#define IDC_DYNACOL10                   1100
#define IDC_DYNACOL11                   1101
#define IDC_DYNACOL12                   1102
#define IDC_DYNACOL13                   1103
#define IDC_DYNACOL14                   1104
#define IDC_DYNACOL15                   1105
#define IDC_DYNACOL16                   1106
#define IDC_INVERTSEL                   1107
#define IDC_ADDSECTION2                 1107
#define IDC_STRY15                      1107
#define IDC_INVERTSEL2                  1108
#define IDC_MOVESECTION                 1109
#define IDC_STRY16                      1110
#define IDC_SPRITELIST2                 1111
#define IDC_ADDSPRITE2                  1112
#define IDC_DELSPRITE2                  1113
#define IDC_BUTTON1                     1114
#define IDC_COLROT                      1114
#define IDC_LIST1                       1115
#define IDC_IDENTIFYDYN                 1115
#define IDC_IDENT                       1115
#define IDC_BUTTON2                     1115
#define IDC_FRUSEMASK                   1116
#define IDC_STRY20                      1116
#define IDC_INVERTSEL3                  1117
#define IDC_SCROLLFILL                  1117
#define IDC_TRIGID                      1118
#define IDC_DELTIME                     1118
#define IDC_ADDTID                      1119
#define IDC_TIMELEN                     1119
#define IDC_DELTID                      1120
#define IDC_DELCOL                      1120
#define IDC_DELMASK                     1121
#define IDC_FRUSESPRITE                 1123
#define IDC_NCOL                        1124
#define IDC_BROWSEIMAGE                 1126
#define IDC_CBPASTE                     1128
#define IDC_VIDEOSLIDER                 1129
#define IDC_CURSORTIME                  1130
#define IDC_TOTALTIME                   1131
#define IDC_SPIN1                       1132
#define IDC_TIMESPIN                    1132
#define IDC_HOURSPIN                    1132
#define IDC_MINSPIN                     1133
#define IDC_HOUR                        1133
#define IDC_SECSPIN                     1134
#define IDC_MINUTE                      1134
#define IDC_HOURSPINIDC_HOURSPIN4       1135
#define IDC_FRMSPIN                     1135
#define IDC_SECOND                      1135
#define IDC_FRAME                       1136
#define IDC_REGULDUR                    1142
#define IDC_INTERV                      1143
#define IDC_FRAMEDUR                    1144
#define IDC_CURFRAMEALL                 1145
#define IDC_CONTRAST                    1151
#define IDC_CONTRAST2                   1152
#define IDC_BRIGHTNESS                  1152
#define IDC_STATICB                     1153
#define IDC_STATICC                     1154
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        269
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1155
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
